services:
  gym-logger.backend:
    container_name: gym-logger.backend
    image: ${DOCKER_REGISTRY-}gymloggerbackend
    build:
      context: .
      dockerfile: gym-logger-backend/Dockerfile
    ports: 
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - gym-logger.database
    networks:
      - backend_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  gym-logger.database:
    container_name: gym-logger.database
    image: postgres:17.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: gym-logger-database
    # shm_size: 128mb
    restart: always
    ports:
      - 5432:5432
    networks:
      - backend_network
    volumes:
      - ./.containers/database:/var/lib/postgresql/data

  gym-logger.pgadmin:
    container_name: gym-logger.pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./.containers/pgadmin-data:/var/lib/pgadmin
    networks:
      - backend_network
    depends_on:
      - gym-logger.database

networks:
  backend_network:
    driver: bridge
